//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWeb.AuthenticationsDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoles
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Role { get; set; }
    
        public virtual tblUsers tblUsers { get; set; }
    }
}
